/**
 * POST /api/cleanverse/travel-rule
 *
 * Generates a Travel Rule compliance report for a transaction.
 * Primary: calls Cleanverse POST /download_travel_rule (AES-CBC encrypted body).
 * Fallback: generates a local FATF Recommendation 16 report from available data
 *           when Cleanverse has no pre-submitted record for this transaction.
 *
 * Body:    { txHash: string; address: string; chain?: string; tokenId?: string; issuerAddress?: string }
 * Returns: { downloadUrl: string } | { report: object } | { error: string }
 */

import { NextRequest, NextResponse } from 'next/server'
import {
  CLEANVERSE_API_URL,
  cleanverseHeaders,
  encryptedBody,
  isCleanverseConfigured,
  RateLimiter,
} from '@/lib/cleanverse-server'

const MONAD_EXPLORER = 'https://testnet.monadexplorer.com'
const INVOICE_NFT_ADDRESS = process.env.NEXT_PUBLIC_INVOICE_NFT_ADDRESS ?? ''

// 10 report requests per address per hour
const rl = new RateLimiter(10, 3_600_000)

interface ReportInput {
  txHash: string
  address: string
  chain: string
  tokenId?: string
  issuerAddress?: string
  settlementToken?: string
  settlementSymbol?: string
}

function localReport({ txHash, address, chain, tokenId, issuerAddress, settlementToken, settlementSymbol }: ReportInput) {
  return {
    format: 'FATF Travel Rule Report',
    version: '1.0',
    standard: 'FATF Recommendation 16',
    generatedAt: new Date().toISOString(),
    reportingVasp: {
      name: 'vino Protocol',
      website: 'https://vino.eduworld.world',
      kybProvider: 'Cleanverse International',
    },
    network: {
      name: 'Monad Testnet',
      chainId: 10143,
      explorerBase: MONAD_EXPLORER,
    },
    transaction: {
      hash: txHash,
      explorerUrl: `${MONAD_EXPLORER}/tx/${txHash}`,
      chain,
    },
    // Originator = the wallet submitting the report (payer/invoice holder)
    originator: {
      walletAddress: address,
      chain,
      kybProtocol: 'Cleanverse A-Pass',
      kybNote: 'Verified at onboarding via Cleanverse A-Pass. CVI status enforced on-chain.',
    },
    // Beneficiary = the invoice issuer (recipient of payment)
    ...(issuerAddress ? {
      beneficiary: {
        walletAddress: issuerAddress,
        chain,
        kybProtocol: 'Cleanverse A-Pass',
        kybNote: 'Invoice issuer. A-Pass verification required to mint on vino Protocol.',
      },
    } : {}),
    ...(tokenId ? {
      invoice: {
        tokenId,
        contractAddress: INVOICE_NFT_ADDRESS,
        explorerUrl: `${MONAD_EXPLORER}/nft/${INVOICE_NFT_ADDRESS}/${tokenId}`,
      },
    } : {}),
    // Settlement asset — the CVA A-Token selected at invoice creation
    ...(settlementToken ? {
      settlementAsset: {
        atoken: settlementToken,
        symbol: settlementSymbol ?? settlementToken,
        protocol: 'Cleanverse CVA (Cleanverse Verified Asset)',
        kybRequired: true,
        note: 'Settlement must occur via the Cleanverse CVA rail. Both parties must hold a valid A-Pass.',
      },
    } : {}),
    compliance: {
      cviProtocol: 'Cleanverse A-Pass (CVI)',
      cvaProtocol: settlementToken ? `Cleanverse Verified Asset — ${settlementSymbol ?? settlementToken}` : 'N/A',
      travelRuleStandard: 'FATF Recommendation 16',
      note: 'Generated by vino Protocol. All parties are subject to Cleanverse A-Pass KYB gating enforced by the MockCVI contract on Monad Testnet.',
    },
  }
}

export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => null) as {
    txHash?: string; address?: string; chain?: string; tokenId?: string; issuerAddress?: string
  } | null
  const txHash           = body?.txHash?.trim()
  const address          = body?.address
  const chain            = body?.chain ?? 'monad'
  const tokenId          = body?.tokenId
  const issuerAddress    = body?.issuerAddress
  const settlementToken  = (body as Record<string, string> | null)?.settlementToken
  const settlementSymbol = (body as Record<string, string> | null)?.settlementSymbol

  if (!txHash || !/^0x[0-9a-fA-F]{64}$/.test(txHash)) {
    return NextResponse.json({ error: 'invalid_tx_hash' }, { status: 400 })
  }
  if (!address || !/^0x[0-9a-fA-F]{40}$/.test(address)) {
    return NextResponse.json({ error: 'invalid_address' }, { status: 400 })
  }
  if (!rl.allow(address.toLowerCase())) {
    return NextResponse.json({ error: 'rate_limited' }, { status: 429 })
  }

  // 1. Try Cleanverse first — they may have a pre-submitted Travel Rule record.
  if (isCleanverseConfigured()) {
    try {
      const raw = await fetch(`${CLEANVERSE_API_URL}/download_travel_rule`, {
        method: 'POST',
        headers: cleanverseHeaders(),
        body: encryptedBody({ txHash, wallet: { chain, address } }),
        signal: AbortSignal.timeout(15_000),
      })
      if (!raw.ok) throw new Error(`HTTP ${raw.status}`)
      const resp = await raw.json() as {
        code: string
        message?: string
        data?: { downloadUrl?: string } | string
      }
      if (resp.code === '0000' && resp.data) {
        const url = typeof resp.data === 'object' ? resp.data.downloadUrl : resp.data
        return NextResponse.json({ downloadUrl: url, source: 'cleanverse' })
      }
      // Non-0000 code = no record in Cleanverse for this tx — fall through to local.
    } catch (err) {
      // Network error — fall through to local report.
      console.warn('[cleanverse/travel-rule] Cleanverse unavailable, generating locally:', err)
    }
  }

  // 2. Generate locally — expected on testnet where no VASP has pre-submitted this tx.
  return NextResponse.json({
    report: localReport({ txHash, address, chain, tokenId, issuerAddress, settlementToken, settlementSymbol }),
    source: 'local',
  })
}
